dcConsData = [
	{name:"소닉링없찐.gif", 	keywords:["링없찐"], 							tags:["소닉"]},
	{name:"소닉결혼반지.png",	keywords:["결혼반지"],						tags:["소닉"]},
	{name:"주인님.png",				keywords:["주인님"],							tags:["미분류"]},
	{name:"겉바속촉.gif",			keywords:["겉바속촉", "가로쉬"],	tags:["와우"]},
	{name:"걸피.png",	 keywords:["걸피"], 	 tags:["걸피"]},
	{name:"걸피납치.png",	 keywords:["걸피납치"], 	 tags:["걸피"]},
	{name:"걸피댄스.gif",	 keywords:["걸피댄스"], 	 tags:["걸피"]},
	{name:"걸피점프.gif",	 keywords:["걸피점프"], 	 tags:["걸피"]},
	{name:"걸피추격.png",	 keywords:["걸피추격"], 	 tags:["걸피"]},
	{name:"고기국수.png",	 keywords:["고기국수가게"], 	 tags:["롤코"]},
	{name:"고기완자탕.png",	 keywords:["고기완자탕가게"], 	 tags:["롤코"]},
	{name:"고인.png",	 keywords:["볼트고인"], 	 tags:["볼트보이"]},
	{name:"고카트.png",	 keywords:["고카트"], 	 tags:["롤코"]},
	{name:"고퀄흠.png",	 keywords:["고퀄흠"], 	 tags:["흠"]},
	{name:"골든무말모.gif",	 keywords:["골든무말모"], 	 tags:["펀즈"]},
	{name:"골든철도죠.gif",	 keywords:["골든철도죠"], 	 tags:["철도"]},
	{name:"골프.png",	 keywords:["골프", "미니골프", "크레이지골프"], 	 tags:["롤코"]},
	{name:"공중.png",	 keywords:["볼트공중"], 	 tags:["볼트보이"]},
	{name:"관람차.png",	 keywords:["관람차"], 	 tags:["롤코"]},
	{name:"관전.png",	 keywords:["볼트관전"], 	 tags:["볼트보이"]},
	{name:"교화됨.gif",	 keywords:["교화됨"], 	 tags:["손님얼굴"]},
	{name:"구와아악.png",	 keywords:["구와아악"], 	 tags:["우리가남이가"]},
	{name:"구토.gif",	 keywords:["구토"], 	 tags:["롤코상황"]},
	{name:"구토.png",	 keywords:["볼트구토"], 	 tags:["볼트보이"]},
	{name:"군인.png",	 keywords:["군인"], 	 tags:[]},
	{name:"귀신의집.png",	 keywords:["귀신의집", "유령의집"], 	 tags:["롤코"]},
	{name:"그안키.png",	 keywords:["그안키"], 	 tags:["레바"]},
	{name:"근엄.png",	 keywords:["볼트근엄"], 	 tags:["볼트보이"]},
	{name:"근육.png",	 keywords:["볼트근육"], 	 tags:["볼트보이"]},
	{name:"기가.png",	 keywords:["기가", "기가코스터"], 	 tags:["롤코"]},
	{name:"기계.png",	 keywords:["볼트기계"], 	 tags:["볼트보이"]},
	{name:"기념품.png",	 keywords:["기념품가게"], 	 tags:["롤코"]},
	{name:"김치워리어.png",	 keywords:["김치워리어"], 	 tags:["펄럭"]},
	{name:"나무.png",	 keywords:["볼트나무"], 	 tags:["볼트보이"]},
	{name:"나선.png",	 keywords:["나선", "나선코스터"], 	 tags:["롤코"]},
	{name:"나선미끄럼틀.png",	 keywords:["나선미끄럼틀"], 	 tags:["롤코"]},
	{name:"나선창렬.gif",	 keywords:["나선창렬"], 	 tags:["롤코창렬"]},
	{name:"남이가1.png",	 keywords:["남이가1"], 	 tags:["우리가남이가"]},
	{name:"남이가2.png",	 keywords:["남이가2"], 	 tags:["우리가남이가"]},
	{name:"네다철.png",	 keywords:["네다철"], 	 tags:["철도", "구독콘"]},
	{name:"네말맞.gif",	 keywords:["네말맞"], 	 tags:["착한"]},
	{name:"넷여친.png",	 keywords:["볼트넷여친"], 	 tags:["볼트보이"]},
	{name:"넷친구.png",	 keywords:["볼트넷친구"], 	 tags:["볼트보이"]},
	{name:"노예일해.png",	 keywords:["노예일해"], 	 tags:["캐피탈리즘"]},
	{name:"누물보.png",	 keywords:["누물보"], 	 tags:["누물보"]},
	{name:"눈물.png",	 keywords:["볼트눈물"], 	 tags:["볼트보이"]},
	{name:"니공원등급.gif",	 keywords:["니공원등급"], 	 tags:["니공원"]},
	{name:"니공원손님.gif",	 keywords:["니공원손님"], 	 tags:["니공원"]},
	{name:"니공원재정.gif",	 keywords:["니공원재정"], 	 tags:["니공원"]},
	{name:"닌자.png",	 keywords:["볼트닌자"], 	 tags:["볼트보이"]},
	{name:"닥쳐.png",	 keywords:["볼트닥쳐"], 	 tags:["볼트보이"]},
	{name:"답답.png",	 keywords:["볼트답답"], 	 tags:["볼트보이"]},
	{name:"대롱.gif",	 keywords:["대롱"], 	 tags:["롤코상황"]},
	{name:"대머리.png",	 keywords:["볼트대머리"], 	 tags:["볼트보이"]},
	{name:"대탈주.gif",	 keywords:["대탈주"], 	 tags:["롤코상황"]},
	{name:"댕댕.gif",	 keywords:["댕댕콘"], 	 tags:["댕댕콘"]},
	{name:"댕댕.png",	 keywords:["볼트댕댕"], 	 tags:["볼트보이"]},
	{name:"더블부스터.gif",	 keywords:["x"], 	 tags:["소닉"]},
	{name:"도넛.png",	 keywords:["도넛가게"], 	 tags:["롤코"]},
	{name:"동정.png",	 keywords:["볼트동정"], 	 tags:["볼트보이"]},
	{name:"두유.png",	 keywords:["두유가게"], 	 tags:["롤코"]},
	{name:"드럼.gif",	 keywords:["우리핵드럼"], 	 tags:["이북리더"]},
	{name:"등골.png",	 keywords:["볼트등골"], 	 tags:["볼트보이"]},
	{name:"딴딴.png",	 keywords:["볼트딴딴"], 	 tags:["볼트보이"]},
	{name:"딸딸.png",	 keywords:["볼트딸딸"], 	 tags:["볼트보이"]},
	{name:"떠남.png",	 keywords:["볼트떠남"], 	 tags:["볼트보이"]},
	{name:"또타.png",	 keywords:["또타"], 	 tags:["철도"]},
	{name:"띠용.png",	 keywords:["볼트띠용"], 	 tags:["볼트보이"]},
	{name:"라이플.png",	 keywords:["볼트라이플"], 	 tags:["볼트보이"]},
	{name:"런치드창렬.gif",	 keywords:["런치드창렬"], 	 tags:["롤코창렬"]},
	{name:"런치드프리폴.png",	 keywords:["런치드프리폴", "자유낙하"], 	 tags:["롤코"]},
	{name:"레모네이드.png",	 keywords:["레모네이드가게"], 	 tags:["롤코"]},
	{name:"레바띠용.png",	 keywords:["레바띠용"], 	 tags:["레바"]},
	{name:"레바탕탕.gif",	 keywords:["레바탕탕"], 	 tags:["레바"]},
	{name:"레바팝콘.png",	 keywords:["레바팝콘"], 	 tags:["레바"]},
	{name:"레이다운.png",	 keywords:["레이다운"], 	 tags:["레바"]},
	{name:"로딩.gif",	 keywords:["로딩"], 	 tags:["소닉"]},
	{name:"롤코공포.png",	 keywords:["롤코공포", "공포"], 	 tags:["롤코상황"]},
	{name:"롤코범죄.png",	 keywords:["롤코범죄", "범죄"], 	 tags:["롤코상황"]},
	{name:"롤코사행성.png",	 keywords:["롤코사행성", "사행성"], 	 tags:["롤코상황"]},
	{name:"롤코선정성.png",	 keywords:["롤코선정성", "선정성"], 	 tags:["롤코상황"]},
	{name:"롤코약물.png",	 keywords:["롤코약물", "약물"], 	 tags:["롤코상황"]},
	{name:"롤코언어.png",	 keywords:["롤코언어", "언어"], 	 tags:["롤코상황"]},
	{name:"롤코펑1.gif",	 keywords:["롴코펑", "롤코펑1"], 	 tags:["롤코상황"]},
	{name:"롤코펑2.gif",	 keywords:["롤코펑2"], 	 tags:["롤코상황"]},
	{name:"롤코폭력성.png",	 keywords:["롤코폭력성", "폭력성"], 	 tags:["롤코상황"]},
	{name:"루저.png",	 keywords:["볼트루저"], 	 tags:["볼트보이"]},
	{name:"루핑.png",	 keywords:["루핑", "루핑코스터"], 	 tags:["롤코"]},
	{name:"루핑창렬.gif",	 keywords:["루핑창렬"], 	 tags:["롤코창렬"]},
	{name:"리버래프트.png",	 keywords:["리버래프트"], 	 tags:["롤코"]},
	{name:"리버래피드.png",	 keywords:["리버래피드"], 	 tags:["롤코"]},
	{name:"리버서.png",	 keywords:["리버서", "리버서코스터"], 	 tags:["롤코"]},
	{name:"리버스펑.gif",	 keywords:["리버스펑"], 	 tags:["롤코상황"]},
	{name:"리버스프리폴.png",	 keywords:["리버스프리폴", "역방향자유낙하"], 	 tags:["롤코"]},
	{name:"리얼싸닉.png",	 keywords:["리얼싸닉"], 	 tags:["소닉"]},
	{name:"림발진.png",	 keywords:["림발진", "림발사"], 	 tags:["롤코"]},
	{name:"마약.png",	 keywords:["볼트마약"], 	 tags:["볼트보이"]},
	{name:"마인.png",	 keywords:["마인", "마인라이드"], 	 tags:["롤코"]},
	{name:"마치.png",	 keywords:["마치"], 	 tags:["아아"]},
	{name:"만두국.png",	 keywords:["만두국가게", "만둣국가게"], 	 tags:["롤코"]},
	{name:"망치.png",	 keywords:["볼트망치"], 	 tags:["볼트보이"]},
	{name:"매우정상.png",	 keywords:["매우정상"], 	 tags:["매우정상"]},
	{name:"멀미1.gif",	 keywords:["멀미1"], 	 tags:["손님얼굴"]},
	{name:"멀미2.gif",	 keywords:["멀미2"], 	 tags:["손님얼굴"]},
	{name:"멀미3.gif",	 keywords:["멀미3"], 	 tags:["손님얼굴"]},
	{name:"멀티디멘션.png",	 keywords:["멀티디멘션", "다차원", "다차원코스터"],   tags:["롤코"]},
	{name:"멋있다.gif",	 keywords:["멋있다"], 	 tags:["착한"]},
	{name:"메이즈.png",	 keywords:["메이즈"], 	 tags:["롤코"]},
	{name:"명상.png",	 keywords:["볼트명상"], 	 tags:["볼트보이"]},
	{name:"모노레일.png",	 keywords:["모노레일"], 	 tags:["롤코"]},
	{name:"모션시뮬레이터.png",	 keywords:["모션시뮬레이터"], 	 tags:["롤코"]},
	{name:"모자.png",	 keywords:["모자가게"], 	 tags:["롤코"]},
	{name:"모형기차.png",	 keywords:["모형기차", "미니철도"], 	 tags:["롤코"]},
	{name:"무궁화.png",	 keywords:["무궁화"], 	 tags:["펄럭"]},
	{name:"무지개깃발.gif",	 keywords:["무지개깃발"], 	 tags:["무지개깃발"]},
	{name:"무표정.gif",	 keywords:["무표정"], 	 tags:["손님얼굴"]},
	{name:"문풍당당1.gif",	 keywords:["문풍당당", "문풍당당1"], 	 tags:["위풍당당"]},
	{name:"문풍당당2.gif",	 keywords:["문풍당당2"], 	 tags:["위풍당당"]},
	{name:"문풍당당3.gif",	 keywords:["문풍당당3"], 	 tags:["위풍당당"]},
	{name:"문풍당당4.gif",	 keywords:["문풍당당4"], 	 tags:["위풍당당"]},
	{name:"문풍당당5.gif",	 keywords:["문풍당당5"], 	 tags:["위풍당당"]},
	{name:"문풍당당6.gif",	 keywords:["문풍당당6"], 	 tags:["위풍당당"]},
	{name:"미니.png",	 keywords:["미니", "미니코스터"], 	 tags:["롤코"]},
	{name:"미니서스펜디드.png",	 keywords:["미니서스펜디드"], 	 tags:["롤코"]},
	{name:"미니헬리콥터.png",	 keywords:["미니헬리콥터"], 	 tags:["롤코"]},
	{name:"바이킹.png",	 keywords:["바이킹"], 	 tags:["롤코"]},
	{name:"박수1.gif",	 keywords:["우리핵박수1"], 	 tags:["이북리더"]},
	{name:"박수2.gif",	 keywords:["우리핵박수2"], 	 tags:["이북리더"]},
	{name:"박수3.gif",	 keywords:["우리핵박수3"], 	 tags:["이북리더"]},
	{name:"방긋.gif",	 keywords:["방긋"], 	 tags:["손님얼굴"]},
	{name:"백조보트.png",	 keywords:["백조보트", "스완보트"], 	 tags:["롤코"]},
	{name:"버그.gif",	 keywords:["버그"], 	 tags:["벤브로드"]},
	{name:"버스딸딸.gif",	 keywords:["버스딸딸"], 	 tags:["버스"]},
	{name:"버지니아.png",	 keywords:["버지니아", "버지니아릴"], 	 tags:["롤코"]},
	{name:"범퍼카.png",	 keywords:["범퍼카", "다젬"], 	 tags:["롤코"]},
	{name:"병신.png",	 keywords:["볼트병신"], 	 tags:["볼트보이"]},
	{name:"병원.png",	 keywords:["병원", "응급실"], 	 tags:["롤코"]},
	{name:"보트.png",	 keywords:["보트", "범퍼보트"], 	 tags:["롤코"]},
	{name:"복창펑1.png",	 keywords:["복창펑", "복창펑1"], 	 tags:["복창펑"]},
	{name:"복창펑2.png",	 keywords:["복창펑2"], 	 tags:["복창펑"]},
	{name:"볼트가정사.png",	 keywords:["볼트가정사"], 	 tags:["볼트보이"]},
	{name:"봅슬레이.png",	 keywords:["봅슬레이", "밥슬레이"], 	 tags:["롤코"]},
	{name:"부활.png",	 keywords:["볼트부활"], 	 tags:["볼트보이"]},
	{name:"불편.png",	 keywords:["불편"], 	 tags:["개비스콘"]},
	{name:"불편불.gif",	 keywords:["불편불", "편불편"], 	 tags:["개비스콘"]},
	{name:"불편해짐.gif",	 keywords:["불편해짐"], 	 tags:["개비스콘"]},
	{name:"불행1.gif",	 keywords:["불행", "불행1"], 	 tags:["손님얼굴"]},
	{name:"불행2.gif",	 keywords:["불행2"], 	 tags:["손님얼굴"]},
	{name:"불행불.gif",	 keywords:["불행불"], 	 tags:["손님얼굴"]},
	{name:"불행해짐.gif",	 keywords:["불행해짐"], 	 tags:["개비스콘"]},
	{name:"비밀친구.png",	 keywords:["볼트비밀친구"], 	 tags:["볼트보이"]},
	{name:"비행접시.png",	 keywords:["비행접시"], 	 tags:["롤코"]},
	{name:"빠따.png",	 keywords:["볼트빠따"], 	 tags:["볼트보이"]},
	{name:"빠요엔.gif",	 keywords:["빠요엔"], 	 tags:["뿌요"]},
	{name:"빨개짐.gif",	 keywords:["빨개짐"], 	 tags:["손님얼굴"]},
	{name:"빨갱이.gif",	 keywords:["빨갱이", "화남"], 	 tags:["손님얼굴"]},
	{name:"빵야.gif",	 keywords:["우리핵빵야"], 	 tags:["이북리더"]},
	{name:"빼액.png",	 keywords:["볼트빼액"], 	 tags:["볼트보이"]},
	{name:"삐뚤어진집.png",	 keywords:["삐뚤어진집", "비틀어진집", "비틀린집"], 	 tags:["롤코"]},
	{name:"사과사탕.png",	 keywords:["사과사탕가게", "토피애플가게"], 	 tags:["롤코"]},
	{name:"사딸라.png",	 keywords:["사딸라", "4딸라"], 	 tags:["야인시대"]},
	{name:"사망.png",	 keywords:["사망"], 	 tags:["사망"]},
	{name:"사이드프릭션.png",	 keywords:["사이드프릭션"], 	 tags:["롤코"]},
	{name:"상하이조.gif",	 keywords:["상하이조"], 	 tags:["야인시대"]},
	{name:"샌드위치.png",	 keywords:["샌드위치가게"], 	 tags:["롤코"]},
	{name:"서스펜디드.png",	 keywords:["서스펜디드", "반전", "반전코스터"], 	 tags:["롤코"]},
	{name:"서스펜디드모노레일.png",	 keywords:["서스펜디드모노레일", "매달린모노레일"], 	 tags:["롤코"]},
	{name:"서커스.png",	 keywords:["서커스"], 	 tags:["롤코"]},
	{name:"선글라스.png",	 keywords:["선글라스가게"], 	 tags:["롤코"]},
	{name:"설명.png",	 keywords:["설명", "설명들갑", "레바설명"], 	 tags:["레바"]},
	{name:"소닉붐.png",	 keywords:["소닉붐"], 	 tags:["소닉"]},
	{name:"소세지.png",	 keywords:["소세지가게"], 	 tags:["롤코"]},
	{name:"솜사탕.png",	 keywords:["솜사탕가게"], 	 tags:["롤코"]},
	{name:"수류탄.png",	 keywords:["볼트수류탄"], 	 tags:["볼트보이"]},
	{name:"수면.png",	 keywords:["볼트수면"], 	 tags:["볼트보이"]},
	{name:"수정과.png",	 keywords:["수정과가게"], 	 tags:["롤코"]},
	{name:"수직낙하.png",	 keywords:["수직낙하", "버티컬드롭"], 	 tags:["롤코"]},
	{name:"스웨그싸닉.png",	 keywords:["스웨그싸닉"], 	 tags:["소닉"]},
	{name:"스웩흠.png",	 keywords:["스웩흠"], 	 tags:["흠"]},
	{name:"스타프루트.png",	 keywords:["스타프루트가게", "스타후르츠가게"], 	 tags:["롤코"]},
	{name:"스탠드업.png",	 keywords:["스탠드업", "스탠드업코스터"], 	 tags:["롤코"]},
	{name:"스티플체이스.png",	 keywords:["스티플체이스"], 	 tags:["롤코"]},
	{name:"스파이럴.png",	 keywords:["스파이럴"], 	 tags:["롤코"]},
	{name:"스페이스링.png",	 keywords:["스페이스링"], 	 tags:["롤코"]},
	{name:"스플래시보트.png",	 keywords:["스플래시보트"], 	 tags:["롤코"]},
	{name:"시무룩.gif",	 keywords:["시무룩"], 	 tags:["손님얼굴"]},
	{name:"신문.png",	 keywords:["볼트신문"], 	 tags:["볼트보이"]},
	{name:"심리.png",	 keywords:["볼트심리"], 	 tags:["볼트보이"]},
	{name:"심영박수.gif",	 keywords:["심영박수"], 	 tags:["야인시대"]},
	{name:"심영박수2.gif",	 keywords:["심영박수2"], 	 tags:["야인시대"]},
	{name:"심영연기.gif",	 keywords:["심영연기"], 	 tags:["야인시대"]},
	{name:"심영폭발.gif",	 keywords:["심영폭발", "폭8"], 	 tags:["야인시대"]},
	{name:"싸닉.png",	 keywords:["싸닉"], 	 tags:["소닉"]},
	{name:"싸닉골든.png",	 keywords:["싸닉골든"], 	 tags:["소닉"]},
	{name:"싸닉나클즈.png",	 keywords:["싸닉나클즈"], 	 tags:["소닉"]},
	{name:"싸닉따일즈.png",	 keywords:["싸닉따일즈"], 	 tags:["소닉"]},
	{name:"싸닉매니아.png",	 keywords:["싸닉매니아"], 	 tags:["소닉"]},
	{name:"싸도우.png",	 keywords:["싸도우"], 	 tags:["소닉"]},
	{name:"쌍안경.gif",	 keywords:["우리핵쌍안경"], 	 tags:["이북리더"]},
	{name:"아닌데.gif",	 keywords:["우리핵아닌데"], 	 tags:["이북리더"]},
	{name:"아아.png",	 keywords:["아아"], 	 tags:["아아"]},
	{name:"아이스크림.png",	 keywords:["아이스크림가게"], 	 tags:["롤코"]},
	{name:"아이스크림콘.png",	 keywords:["아이스크림콘가게"], 	 tags:["롤코"]},
	{name:"아이스티.png",	 keywords:["아이스티가게"], 	 tags:["롤코"]},
	{name:"아킴보.png",	 keywords:["볼트아킴보"], 	 tags:["볼트보이"]},
	{name:"안내소.png",	 keywords:["안내소"], 	 tags:["롤코"]},
	{name:"안녕.gif",	 keywords:["우리핵안녕"], 	 tags:["이북리더"]},
	{name:"안녕.png",	 keywords:["안녕"], 	 tags:["똘이"]},
	{name:"안마.png",	 keywords:["볼트안마"], 	 tags:["볼트보이"]},
	{name:"암드.png",	 keywords:["암드", "amd"], 	 tags:["로고"]},
	{name:"양탄자.png",	 keywords:["양탄자"], 	 tags:["롤코"]},
	{name:"어케이겼노.gif",	 keywords:["어케이겼노"], 	 tags:["히오스"]},
	{name:"어케했노.gif",	 keywords:["어케했노"], 	 tags:["히오스"]},
	{name:"어푸.gif",	 keywords:["어푸"], 	 tags:["롤코상황"]},
	{name:"엄격.png",	 keywords:["볼트엄격"], 	 tags:["볼트보이"]},
	{name:"에라.png",	 keywords:["에라", "에라모겠", "에라몰겠"], 	 tags:["레바"]},
	{name:"에어파워드버티컬.png",	 keywords:["에어파워드버티컬"], 	 tags:["롤코"]},
	{name:"엔터프라이즈.png",	 keywords:["엔터프라이즈"], 	 tags:["롤코"]},
	{name:"엘리베이터.png",	 keywords:["엘리베이터"], 	 tags:["롤코"]},
	{name:"연기.gif",	 keywords:["연기"], 	 tags:["롤코상황"]},
	{name:"연설.png",	 keywords:["볼트연설"], 	 tags:["볼트보이"]},
	{name:"연주.png",	 keywords:["볼트연주"], 	 tags:["볼트보이"]},
	{name:"영화관.png",	 keywords:["영화관", "3d시네마"], 	 tags:["롤코"]},
	{name:"예수.png",	 keywords:["볼트예수"], 	 tags:["볼트보이"]},
	{name:"예풍당당.gif",	 keywords:["예풍당당"], 	 tags:["위풍당당"]},
	{name:"오케이땡큐.png",	 keywords:["오케이땡큐"], 	 tags:["야인시대"]},
	{name:"옴닉.png",	 keywords:["인공지능", "옴닉"], 	 tags:["인공지능"]},
	{name:"와아.png",	 keywords:["레바와아", "와아"], 	 tags:["레바"]},
	{name:"와일드마우스.png",	 keywords:["와일드마우스"], 	 tags:["롤코"]},
	{name:"왜곡흠.gif",	 keywords:["왜곡흠"], 	 tags:["흠"]},
	{name:"우든.png",	 keywords:["우든", "우든코스터", "목재"], 	 tags:["롤코"]},
	{name:"우든와일드광산.png",	 keywords:["우든와일드광산", "목재와일드광산"], 	 tags:["롤코"]},
	{name:"우든와일드마우스.png",	 keywords:["우든와일드마우스", "목재와일드마우스"], 	 tags:["롤코"]},
	{name:"우든트위스터.png",	 keywords:["우든트위스터", "목재트위스터"], 	 tags:["롤코"]},
	{name:"우승.png",	 keywords:["볼트우승"], 	 tags:["볼트보이"]},
	{name:"워터슬라이드.png",	 keywords:["워터슬라이드"], 	 tags:["롤코"]},
	{name:"워터코스터.png",	 keywords:["워터코스터", "워터롤러코스터"], 	 tags:["롤코"]},
	{name:"유령기차.png",	 keywords:["유령기차", "유령열차"], 	 tags:["롤코"]},
	{name:"음료수.png",	 keywords:["음료수가게"], 	 tags:["롤코"]},
	{name:"음주.png",	 keywords:["볼트음주"], 	 tags:["볼트보이"]},
	{name:"이제좀.png",	 keywords:["이제좀", "레바이제좀"], 	 tags:["레바"]},
	{name:"이지붐.jpg",	 keywords:["이지붐"], 	 tags:["이지"]},
	{name:"이풍당당1.gif",	 keywords:["이풍당당", "이풍당당1"], 	 tags:["위풍당당"]},
	{name:"이풍당당2.gif",	 keywords:["이풍당당2"], 	 tags:["위풍당당"]},
	{name:"이풍당당3.gif",	 keywords:["이풍당당3"], 	 tags:["위풍당당"]},
	{name:"인버티드.png",	 keywords:["인버티드", "뒤집힌"], 	 tags:["롤코"]},
	{name:"인텔.png",	 keywords:["인텔"], 	 tags:["로고"]},
	{name:"입체회전흠.gif",	 keywords:["입체회전흠", "회전흠3"], 	 tags:["흠"]},
	{name:"자기과시.png",	 keywords:["자기과시"], 	 tags:["자기과시"]},
	{name:"자본.png",	 keywords:["볼트자본"], 	 tags:["볼트보이"]},
	{name:"자살.png",	 keywords:["볼트자살"], 	 tags:["볼트보이"]},
	{name:"자이로드롭.png",	 keywords:["자이로드롭", "로토드롭"], 	 tags:["롤코"]},
	{name:"자이로창렬.gif",	 keywords:["자이로창렬"], 	 tags:["롤코창렬"]},
	{name:"자전거.png",	 keywords:["자전거"], 	 tags:["롤코"]},
	{name:"잔짜잔.gif",	 keywords:["잔짜잔"], 	 tags:["히오스"]},
	{name:"잠수.gif",	 keywords:["잠수", "대롱"], 	 tags:["롤코상황"]},
	{name:"잠수2.gif",	 keywords:["잠수2"], 	 tags:["롤코상황"]},
	{name:"잠수3.gif",	 keywords:["잠수3", "의자왕"], 	 tags:["롤코상황"]},
	{name:"잡았다요놈.png",	 keywords:["잡았다요놈", "포돌이", "철컹철컹"], 	 tags:["경찰"]},
	{name:"장전.png",	 keywords:["볼트장전"], 	 tags:["볼트보이"]},
	{name:"저격.png",	 keywords:["볼트저격"], 	 tags:["볼트보이"]},
	{name:"저퀄흠.png",	 keywords:["저퀄흠"], 	 tags:["흠"]},
	{name:"전기톱.png",	 keywords:["볼트전기톱"], 	 tags:["볼트보이"]},
	{name:"전망탑.png",	 keywords:["전망탑", "전망대"], 	 tags:["롤코"]},
	{name:"전범목마.png",	 keywords:["전범목마"], 	 tags:["롤코"]},
	{name:"전차창렬.png",	 keywords:["전차창렬"], 	 tags:["롤코창렬"]},
	{name:"절망.png",	 keywords:["볼트절망"], 	 tags:["볼트보이"]},
	{name:"점프.gif",	 keywords:["점프"], 	 tags:["롤코상황"]},
	{name:"정신승리.png",	 keywords:["정신승리"], 	 tags:["누물보"]},
	{name:"제어불능.gif",	 keywords:["제어불능"], 	 tags:["롤코상황"]},
	{name:"주니어.png",	 keywords:["주니어", "주니어코스터"], 	 tags:["롤코"]},
	{name:"주먹.png",	 keywords:["볼트주먹"], 	 tags:["롤코"]},
	{name:"주사.png",	 keywords:["볼트주사"], 	 tags:["볼트보이"]},
	{name:"진지.png",	 keywords:["볼트진지"], 	 tags:["볼트보이"]},
	{name:"짜잔.gif",	 keywords:["짜잔"], 	 tags:["히오스"]},
	{name:"짝짝짝.gif",	 keywords:["짝짝짝", "박수"], 	 tags:["롤코상황"]},
	{name:"짱이야.gif",	 keywords:["짱이야"], 	 tags:["착한"]},
	{name:"처형.png",	 keywords:["볼트처형"], 	 tags:["볼트보이"]},
	{name:"철도청.png",	 keywords:["철도청"], 	 tags:["철도", "구독콘"]},
	{name:"체어리프트.png",	 keywords:["체어리프트", "의자식리프트"], 	 tags:["롤코"]},
	{name:"초극한.png",	 keywords:["초극한"], 	 tags:["롤코상황"]},
	{name:"초특가무궁화.gif",	 keywords:["초특가무궁화"], 	 tags:["철도"]},
	{name:"촉수.png",	 keywords:["촉수가게"], 	 tags:["롤코"]},
	{name:"축하해.gif",	 keywords:["축하해"], 	 tags:["착한"]},
	{name:"치킨.png",	 keywords:["치킨가게"], 	 tags:["롤코"]},
	{name:"치킨너겟.png",	 keywords:["치킨너겟가게"], 	 tags:["롤코"]},
	{name:"침대.png",	 keywords:["볼트침대"], 	 tags:["볼트보이"]},
	{name:"카누.png",	 keywords:["카누"], 	 tags:["롤코"]},
	{name:"카라이드.png",	 keywords:["카라이드", "차량"], 	 tags:["롤코"]},
	{name:"커피.png",	 keywords:["커피가게"], 	 tags:["롤코"]},
	{name:"컴온.png",	 keywords:["볼트컴온"], 	 tags:["볼트보이"]},
	{name:"컴팩트인버티드.png",	 keywords:["컴팩트인버티드", "반전수직셔틀"], 	 tags:["롤코"]},
	{name:"케이크.png",	 keywords:["케이크가게"], 	 tags:["롤코"]},
	{name:"쿠키.png",	 keywords:["쿠키가게"], 	 tags:["롤코"]},
	{name:"탄광.png",	 keywords:["탄광", "광산열차"], 	 tags:["롤코"]},
	{name:"탈주.gif",	 keywords:["탈주"], 	 tags:["롤코상황"]},
	{name:"탑스핀.png",	 keywords:["탑스핀"], 	 tags:["롤코"]},
	{name:"태극기.png",	 keywords:["태극기"], 	 tags:["펄럭"]},
	{name:"태극흠.png",	 keywords:["태극흠"], 	 tags:["흠"]},
	{name:"토끼.png",	 keywords:["볼트토끼"], 	 tags:[]},
	{name:"토끼공듀1.png",	 keywords:["토끼공듀"], 	 tags:["토끼공듀"]},
	{name:"토끼공듀2.png",	 keywords:["망겜이다"], 	 tags:["토끼공듀"]},
	{name:"통수.png",	 keywords:["볼트통수"], 	 tags:["볼트보이"]},
	{name:"투시.png",	 keywords:["볼트투시"], 	 tags:["볼트보이"]},
	{name:"투정.gif",	 keywords:["우리핵투정"], 	 tags:["이북리더"]},
	{name:"투창.png",	 keywords:["볼트투창"], 	 tags:["볼트보이"]},
	{name:"튀김쌀국수.png",	 keywords:["튀김쌀국수가게"], 	 tags:["롤코"]},
	{name:"트램.png",	 keywords:["트램", "전차"], 	 tags:["롤코"]},
	{name:"트럼프끄덕.gif",	 keywords:["트럼프끄덕", "럼프끄덕"], 	 tags:["트럼프"]},
	{name:"트럼프따봉.png",	 keywords:["트럼프따봉", "럼프따봉"], 	 tags:["트럼프"]},
	{name:"트럼프리듬.gif",	 keywords:["트럼프리듬", "럼프리듬"], 	 tags:["트럼프"]},
	{name:"트위스터.png",	 keywords:["트위스터"], 	 tags:["롤코"]},
	{name:"트위스트.png",	 keywords:["트위스트"], 	 tags:["롤코"]},
	{name:"트풍당당.gif",	 keywords:["트풍당당"], 	 tags:["트수"]},
	{name:"티셔츠.png",	 keywords:["티셔츠가게"], 	 tags:["롤코"]},
	{name:"파산.png",	 keywords:["파산"], 	 tags:["캐피탈리즘"]},
	{name:"파오후.png",	 keywords:["볼트파오후"], 	 tags:["볼트보이"]},
	{name:"파킨.png",	 keywords:["파킨"], 	 tags:["캐피탈리즘"]},
	{name:"팝콘.png",	 keywords:["팝콘", "레바팝콘"], 	 tags:["레바"]},
	{name:"팝콘레바.png",	 keywords:["팝콘레바"], 	 tags:["레바"]},
	{name:"펄럭.png",	 keywords:["볼트펄럭"], 	 tags:["볼트보이"]},
	{name:"펄럭1.gif",	 keywords:["펄럭", "펄럭1"], 	 tags:["펄럭"]},
	{name:"펄럭2.gif",	 keywords:["펄럭2"], 	 tags:["펄럭"]},
	{name:"편안.png",	 keywords:["편안"], 	 tags:["개비스콘"]},
	{name:"편안해짐.gif",	 keywords:["편안해짐"], 	 tags:["개비스콘"]},
	{name:"포기.png",	 keywords:["볼트포기"], 	 tags:["볼트보이"]},
	{name:"폴짝.png",	 keywords:["폴짝"], 	 tags:["캐피탈리즘"]},
	{name:"풍선.png",	 keywords:["풍선가게"], 	 tags:["롤코"]},
	{name:"프레첼.png",	 keywords:["프레첼가게"], 	 tags:["롤코"]},
	{name:"플라잉.png",	 keywords:["플라잉", "플라잉코스터"], 	 tags:["롤코"]},
	{name:"플라잉턴.png",	 keywords:["플라잉턴", "플라잉턴코스터"], 	 tags:["롤코"]},
	{name:"플로어리스.png",	 keywords:["플로어리스", "바닥없는"], 	 tags:["롤코"]},
	{name:"피곤.gif",	 keywords:["피곤"], 	 tags:["손님얼굴"]},
	{name:"피자.png",	 keywords:["피자가게"], 	 tags:["롤코"]},
	{name:"하트라인.gif",	 keywords:["하트라인", "하트라인트위스터"], 	 tags:["롤코"]},
	{name:"핫도그.png",	 keywords:["핫도그가게"], 	 tags:["롤코"]},
	{name:"핫산.png",	 keywords:["볼트핫산"], 	 tags:["볼트보이"]},
	{name:"핫산발상.png",	 keywords:["핫산발상"], 	 tags:["핫산"]},
	{name:"핫산쾅.png",	 keywords:["핫산쾅"], 	 tags:["핫산"]},
	{name:"핫산펑.png",	 keywords:["핫산펑"], 	 tags:["핫산"]},
	{name:"핫초코.png",	 keywords:["핫초코가게"], 	 tags:["롤코"]},
	{name:"햄버거.png",	 keywords:["햄버거가게"], 	 tags:["롤코"]},
	{name:"행복1.gif",	 keywords:["행복", "행복1"], 	 tags:["손님얼굴"]},
	{name:"행복2.gif",	 keywords:["행복2"], 	 tags:["손님얼굴"]},
	{name:"행복해짐.gif",	 keywords:["행복해짐"], 	 tags:["손님얼굴"]},
	{name:"행불행.gif",	 keywords:["행불행"], 	 tags:["손님얼굴"]},
	{name:"형이왜.png",	 keywords:["형이왜"], 	 tags:["형이왜"]},
	{name:"혼란앵무.gif",	 keywords:["혼란앵무"], 	 tags:["앵무"]},
	{name:"혼란흠.gif",	 keywords:["혼란흠"], 	 tags:["흠"]},
	{name:"화나짐.gif",	 keywords:["화나짐"], 	 tags:["손님얼굴"]},
	{name:"화염병.png",	 keywords:["볼트화염병"], 	 tags:["볼트보이"]},
	{name:"화장실.png",	 keywords:["화장실"], 	 tags:["롤코"]},
	{name:"화풀림.gif",	 keywords:["화풀림", "평온해짐"], 	 tags:["손님얼굴"]},
	{name:"환승.png",	 keywords:["환승"], 	 tags:["철도"]},
	{name:"활활.png",	 keywords:["볼트활활"], 	 tags:["볼트보이"]},
	{name:"회전목마.png",	 keywords:["회전목마"], 	 tags:["롤코"]},
	{name:"회전흠.gif",	 keywords:["회전흠", "회전흠1"], 	 tags:["흠"]},
	{name:"회전흠2.gif",	 keywords:["회전흠2"], 	 tags:["흠"]},
	{name:"후룸라이드.png",	 keywords:["후룸라이드", "후룸"], 	 tags:["롤코"]},
	{name:"흠.png",	 keywords:["흠"], 	 tags:["흠"]},
	{name:"흠석.png",	 keywords:["흠석"], 	 tags:["흠"]},
	{name:"흠흠흠.png",	 keywords:["흠흠흠"],		 tags:["흠"]},
	{name:"히사시부리.png",	 keywords:["히사시부리"], 	 tags:["롤코"]},
	{name:"히히못나가.gif",	 keywords:["히히못나가"], 	 tags:["롤코상황"]},
	{name:"KT.png",	 keywords:["KT", "케이티"], 	 tags:["로고"]},
	{name:"U+.png",	 keywords:["U+", "유플", "엘지"], 	 tags:["로고"]},
	{name:"360도바이킹.png",	 keywords:["360도바이킹"], 	 tags:["롤코"]},
	{name:"ATM.png",	 keywords:["ATM"], 	 tags:["롤코"]},
	{name:"KTX.png",	 keywords:["KTX"], 	 tags:["철도"]},
	{name:"SKB.png",	 keywords:["SKB"], 	 tags:["로고"]},
	{name:"SRT.png",	 keywords:["SRT"], 	 tags:["철도"]},
	{name:"b풍당당.gif",	 keywords:["b풍당당"], 	 tags:["벤브로드"]},
	{name:"가능.png",	 keywords:["가능"], 	 tags:["철도"]},
	{name:"감자칩.png",	 keywords:["감자칩가게"], 	 tags:["롤코"]},
	{name:"감자튀김.png",	 keywords:["감자튀김가게"], 	 tags:["롤코"]},
	{name:"갸아악.png",	 keywords:["갸아악"], 	 tags:["우리가남이가"]},
	{name:"결혼.png",	 keywords:["볼트결혼"], 	 tags:["볼트보이"]}
 ];

